//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Image
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class netuEntities3 : DbContext
    {
        private static netuEntities3 _con;
        public netuEntities3()
            : base("name=netuEntities3")
        {
        }
        public static netuEntities3 Got()
        {
            if (_con==null)
            {
                _con = new netuEntities3();
            }
            return _con;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Image3> Image3 { get; set; }
    }
}
